### ISSUE TITLE
Suggestion: Separate config options for Ladder Tweaks

### ISSUE THREAD

**Issue by Brickwrath** [sachingorkar102/tweakin#1]
The current config is configured where:
```
Ladders are slightly tweaked to improve your laddering experience:
  Right clicking a ladder with another one will place it, allowing you to drop ladders down without risking falling to your death.
  Shift+right clicking any end of ladder will allow you to reach the another end, resulting in quick climb
```
Users that want the ability to right-click-place a ladder at down (the first option) but do **not** want the second option (or vice-versa) would likely appreciate the ability to take one, the other, or both of these features.

This was suggested because I love these tweaks, but the "shift-right-click ladder teleport" is a dealbreaker for using this one, but I'd love the place-lower-ladders feature still  :/

Thank you for your time and consideration!  Awesome work!

**Comment by sachingorkar102** [comment]
Ok i will look for a universal config option for both but there are two permission for both tweaks

**Comment by sachingorkar102** [comment]
Todo add universal option

**Comment by sachingorkar102** [comment]
added in 1.9 update
