### ISSUE TITLE
Permissions don't work

### ISSUE THREAD

**Issue by sagudelo1200** [sachingorkar102/tweakin#10]
Oh! what a good job, excellent spigot plugin, but...

Permissions are granted by default to all users of the server, so they can access any active feature of the plugin

This affects when allowing certain settings to users of a certain specific rank such as VIP.

Can you modify this so that no user has the default permissions and must be added manually to the ranges? additionally, you can put a line in config.yml that allows giving all these by default (in case someone requires it)

Thanks!

**Comment by sachingorkar102** [comment]
Sounds pretty specific and unnecessary option/extra step
