### ISSUE TITLE
Feature Request: Armorstand hands

### ISSUE THREAD

**Issue by sagudelo1200** [sachingorkar102/tweakin#14]
I reiterate, excellent plugin and improving!

I think it would be interesting to have a feature that allows the armor stands to have hands, to put objects on them, this could be done by simply pressing 'Shift + Right Click' on the stand with 2 sticks, and let him drop both sticks when he is destroyed, I hope it can be added Thank you very much for the work you do!

**Comment by sachingorkar102** [comment]
Already planned, have a look at trello board ;)
