### ISSUE TITLE
Suggestion: Animal Panic Cooldown

### ISSUE THREAD

**Issue by Brickwrath** [sachingorkar102/tweakin#15]
Currently when animals witness an attack and flee, they continually flee the player until they log out.
It would be a nice QoL update in my opinion if there was a config option to make the effect also wear off after some time, **or** a radius option where animals "forgive" the player after the leave a certain distance.
(It's a little odd in animal pens; attack one livestock and they'll panic the rest of your play session)

Either approach would be awesome, and greatly appreciated!

**Comment by sachingorkar102** [comment]
changed behaviour in 2.5

**Comment by Brickwrath** [comment]
I appreciate the response and effort, but it seems I poorly explained the intention in my posting...
The issue/focus was _not_ that bred animals were an issue, but rather that all animals just flee forever until re-log.
The changes in 2.5, I'm sorry to say, removed enough value from the animal fleeing tweak that it's now just better disabled (for our players based on feedback, anyways)

**To pass along player feedback:**
1) Players *liked* the panic that happened in their animal pens when one was attacked; it made sense and was greatly enjoyed.
2) Players *disliked* that after that, animals just continued to flee forever.
3) Players are now just re-logging to disable the effect; many have asked why it doesn't just "wear off" over time.
(players are clearly confused, expecting the effect to cool off eventually for both wild and tamed animals)
4) The intention/focus was for a timer or cooldown for the effect for a more natural and better gameplay experience; bred animals fleeing was enjoyed by all players I've polled.
5) If a cooldown can't/won't be considered, at least a config option to toggle if bred animals would flee as well would be appreciated to restore its enjoyed functionality.

Sorry for my miscommunication, and genuinely sorry to have to pass along the feedback that this latest change was not an in-game improvement (in our opinion, anyways).  I really appreciate your work and dedication, and hope to continue watching this amazing project continue to grow and improve!

**Comment by sachingorkar102** [comment]
Uhmm, i might have to rewrite the entire flee mechanic for it which i was avoiding but oh well this is what we are doing

**Comment by Brickwrath** [comment]
>_<
I was hoping it wasn't a big thing like that, sorry to pester so much.
Hopefully you hear my intentions to help polish this to be the best it can be, and know that I love and appreciate this plugin and the work that goes into it! (it's answered so many little "tweaks" I've hope for after _years_)

**Comment by sachingorkar102** [comment]
now dont open it again, i am done with this tweak lol
