### ISSUE TITLE
BUG/Suggestion: Users lacking wrap-around build perms still see its ghost block

### ISSUE THREAD

**Issue by Brickwrath** [sachingorkar102/tweakin#17]
This _feels_ like a bug, (if it's not, then consider this a Suggestion I guess?) but players that lack permission to use the wrap-around block placement still see the awesome "ghost block" showing where to place it.
It would be a much better play experience if viewing that block required the use permission.

**Comment by sachingorkar102** [comment]
uhm the highlight permission is different `tweakin.reacharound.highlight`
also players should relogin if the permission was changed when they were online

**Comment by Brickwrath** [comment]
Upon further investigation, from what I can tell after a player changes dimension the highlight starts appearing for them, permission or not.
There are currently NO users in this SMP with the `tweakin.reachround.highlight` (including myself) and many report seeing it, especially in the Nether.

To reproduce (what I'm seeing anyway):
1) Join without the view permission.
2) Make a nether portal, go through it.
3) Attempt to utilize the "Reach Around" tweak, and the highlight will appear.
4) Relogin (no permission changes) and the highlight no longer appears.
5) Pass through the nether portal.
6) Attempt to utilize the "Reach Around" tweak, and the highlight begins appearing again.
7) Relogin (no permission changes) and the highlight no longer appears.

Hope this helps!

**Comment by sachingorkar102** [comment]
i am sorry but i cant replicate the issue as you described, i dont see any highlights after changing dimension(without permission)

**Comment by Brickwrath** [comment]
When the permission is directly _denied_, the issue seems to go away; but if the reacharound permissions are undefined for a user, it seems to come through.
Denying the permission solves it, so unless you want to investigate the behavior further it's "solved" like that.
