### ISSUE TITLE
Suggestion: Permissions per Tweak

### ISSUE THREAD

**Issue by Brickwrath** [sachingorkar102/tweakin#2]
Permissions per-tweak would allow server admins to have better control over various play experiences.
(for example, giving a way for players to individually opt in and out of a feature, such as right-clicking armor in an inventory to swap it)

Other applications might be disabling the ability to "burn vine ends" for *most* players, but allowing OPs or something the feature.

Thank you for your work and consideration!

**Comment by sachingorkar102** [comment]
There already exists each permission for tweaks look into config.yml for more info closing the issue
