### ISSUE TITLE
Request: additional permission nodes

### ISSUE THREAD

**Issue by sagudelo1200** [sachingorkar102/Tweakin#28]
I suggest adding 2 permissions nodes for the enchantment table as I don't see any in the config file, on github or in my permissions plugin autocompleter

would be the following
tweakin.lapisintable: allows you to store the lapis on the table
tweakin.storeitemintable: allows you to store the item on the enchantment table

additionally it would not hurt to review and add permission nodes to each tweakin since it would be useful when allowing / denying in the configuration of ranges of the servers

**Comment by sachingorkar102** [comment]
Huh? I didnt understood the last point
Also mind joining my discord its easy to communicate

**Comment by sachingorkar102** [comment]
I will TRY to add that
No promises tho as its not player related its block related tweak

**Comment by sachingorkar102** [comment]
Each tweak has correct and sufficient permissions in my opinion, unnecessary permissions are not needed
