### ISSUE TITLE
Suggestions: Rotation Wrench

### ISSUE THREAD

**Issue by Brickwrath** [sachingorkar102/tweakin#3]
Love the rotation wrench!
I know it's super-new, but couldn't resist requesting some additional configuration for it.
1) It'd be awesome to have a `craftable: true` config option in case the wrench should not be craftable in-game.
(Would be a nicer alternative to setting the crafting recipe to something uncraftable manually, but really just a QoL thing)
2) A `/tweakin wrench <player>` command or something like it to give it to the player.
(This would offer much more compatibility with other systems, like shop plugins that could run a command on purchase, as well as saving ops/server-builders the time to craft it instead of just *get* it)

Thanks again for your time and work!

**Comment by sachingorkar102** [comment]
Alright i was thinking of give command for items anyways as the next tweaks in 3-4 future updates will include item addition 
Also will add craftable option to each item no worries ;)

**Comment by sachingorkar102** [comment]
added in 0.8 update
closing the issue
