### ISSUE TITLE
Was middle clicked changed in 1.18.1?

### ISSUE THREAD

**Issue by ryantheleach** [sachingorkar102/Tweakin#34]
https://github.com/sachingorkar102/Tweakin/commit/a5983f0ff61b6711dddbe72c73e68c92056f0b52

Is middle click still possible by changing the config? I've been having difficulty in a different plugin with using the middle click, and was wondering what you discovered.

**Comment by TheClassic36** [comment]
I'm not able to help with your issue but I can provide some information. Yes, middle-click was changed in 1.18 to fix this issue: https://bugs.mojang.com/browse/MC-46584

**Comment by ryantheleach** [comment]
That's what I was after, Thanks!
