### ISSUE TITLE
Suggestion: Rotation Wrench Durability

### ISSUE THREAD

**Issue by Brickwrath** [sachingorkar102/tweakin#5]
In order to make the rotation wrench more "survival-like", a config option for a limited number of uses from the Rotation Wrench could be cool.
Such as `uses: 32` would allow a player to craft a wrench, with a lore line or something of "32 uses remaining" and it drops once a use; at 0, the item breaks.
Config option of `uses: 0` or something could disable this feature or something.

**Comment by sachingorkar102** [comment]
Thats nice one
Will add that in next one
Also why not join my discord :)

**Comment by sachingorkar102** [comment]
added in 1.2
