### ISSUE TITLE
Bug: Lapis Duplication Using Enchantment Tables

### ISSUE THREAD

**Issue by Sukiyami** [sachingorkar102/tweakin#6]
Currently, if lapis is stored in an enchantment table it is possible to duplicate it. This is achieved by having a player open the enchantment table whilst another player already has it open (lapis must have been stored and the table closed prior to this), both players may then retrieve the lapis
A similar method is also able to delete lapis, by having a player insert lapis into the table whilst another player already has an empty table open. If the empty table is closed second, the lapis stored in the table is deleted

I assume this is due to the enchantment table inventory being client side, so a possible fix may be preventing more than one player from opening the enchantment table at the same time

**Comment by sachingorkar102** [comment]
Thank you for reporting :)
And yes i am going to do the same thing as suggested

**Comment by sachingorkar102** [comment]
fixed in latest release
