### ISSUE TITLE
Nether Portal Coordinates doesn't take dimension_type coordinate_scale into account

### ISSUE THREAD

**Issue by LinusLeonard** [sachingorkar102/Tweakin#62]
Nether to Overworld travel distance ratio can be changed using data packs by setting a different `coordinate_scale` in a file in data/minecraft/dimension_type. See my datapack [here](https://github.com/LinusLeonard/minecraft-data-packs/tree/main/nether-travel-ratio-1-to-4) where I've set coordinate_scale from the default 8.0 to 4.0 for Nether (i.e. travel distance ratio is effectively doubled that of vanilla).

When using a compass on a Nether Portal where the travel distance ratio is changed, the wrong corresponding coordinates are shown. Example image below, where I have built a portal at 1000,1000. Compass shows 125,125, but since I'm using a 4.0 ratio it should be 250,250. 

<img width="920" alt="example" src="https://github.com/sachingorkar102/Tweakin/assets/10797204/f8a663f1-c23f-42e1-a42c-7f6c76f64cb8">

**Comment by sachingorkar102** [comment]
I actually didnt know such datapack existed, i will add a option to set the scale

**Comment by sachingorkar102** [comment]
fixed in efc7f823196068b075f354712550f761c8433902
