### ISSUE TITLE
New feature suggestions

### ISSUE THREAD

**Issue by SueFox** [sachingorkar102/Tweakin#69]
hey, do you know SimpleLeather or JRFTL(Just Another Rotten Flesh to Leather)?
https://www.curseforge.com/minecraft/mc-mods/simpleleather
https://www.curseforge.com/minecraft/mc-mods/just-another-rotten-flesh-to-leather-mod
They are mods, but my server can't install mods, so could you please add a new feature to let the rotten flesh be burned into leather?

I find a plugin which has the feature with open source: 
https://www.spigotmc.org/resources/expandedenchants.98780/ 
https://github.com/Loikas/MinecraftPlugins

I think this may be helpful for you

**Comment by sachingorkar102** [comment]
its already a [recipe](https://github.com/sachingorkar102/Tweakin/blob/ab3429813ffa99b01608bc55758b31f729b3529d/src/main/resources/custom-recipes.yml#L121) just enable it in [custom-recipes.yml](https://github.com/sachingorkar102/Tweakin/blob/master/src/main/resources/custom-recipes.yml), and also enable the tweak [more-recipes](https://github.com/sachingorkar102/Tweakin/blob/ab3429813ffa99b01608bc55758b31f729b3529d/src/main/resources/config.yml#L672)
