### ISSUE TITLE
A bug or my misunderstanding of the English about Crafting-Table-On-Stick

### ISSUE THREAD

**Issue by SueFox** [sachingorkar102/Tweakin#70]
```
  # if set to true player will be able to use open crafting interface by just using hotkey on crafting table item in inventory
  works-with-crafting-table: false
```
Is it mean if this set to false then i can't open the crafting interface by using hotkey on the stick?
And I saw it in the introduction located on the Spigot webpage that:

> the behavior can be added to crafting table item itself too by setting _works-with-crafting-table_ to true 

So I think this represents what it means...?

If true, this configuration don't work
If false, this means that even with the help of a translator, I am unable to understand the meaning of this English paragraph. I apologize for any inconvenience caused.

**Comment by sachingorkar102** [comment]
if set to true, you can use the hotkey on any "crafting table block" item in your inventory instead of just crafting table on stick item from tweakin

**Comment by SueFox** [comment]
> if set to true, you can use the hotkey on any "crafting table block" item in your inventory instead of just crafting table on stick item from tweakin

oh...Thank you for your explanation

**Comment by sachingorkar102** [comment]
why delete? just set it to false
