### ISSUE TITLE
Suggestion: Additional permissions/settings for Slime in a Bucket

### ISSUE THREAD

**Issue by Brickwrath** [sachingorkar102/tweakin#8]
Such a great resource pack and feature addition!

It'd give a lot more customization options if a separate permission existed such as `tweakin.slimebucket.detect` for if the player's slime-in-a-bucket is allowed to display slime chunks or not.

Also, a config option to disable the detection feature, but keep the slime-in-bucket element might also be nice (but this can be achieved by just setting the detected model to the same as undetected, it just doesn't spare the plugin's efforts this way.
(My players would *love* to be able to bucket and transport slimes, but we're not the kind of server to have a slime-chunk detector, you know?)

**Comment by sachingorkar102** [comment]
Huh? The permission already exists 
Look into config section for more info
Closing

**Comment by Brickwrath** [comment]
This is the config section for slime-in-bucket from Tweakin v.1.7:
```# Use of Resource pack is important [https://github.com/sachingorkar102/Tweakin-Resource-Pack]
# disable this if you dont use resource packs on server.
# Right clicking a tiny(size 1) slime with a bucket puts it in there.
# It remains quiet, but will start jumping inside the bucket if you find yourself in a slime chunk.
# The slime can also be deployed back into the world by right clicking on a block.
# Permission:
  # tweakin.slimebucket.pickup: permission to pickup slime when right clicked with empty bucket
slime-in-bucket:
  enabled: true
  black-list-worlds: []
  # Custom Model data that will be used when the item is not in slime chunk
  model-undetected: 103
  # Custom Model data that will be used when the item is in a slime chunk
  model-detected: 104
  item:
    id: 'SLIME_BALL'
    display: '&fSlime in a Bucket'
    lore:
    - '&aA baby slime in a bucket.'
    - '&aAttack to dump it out.'
    ```
    Only the permission `tweakin.slimebucket.pickup` is listed.

**Comment by sachingorkar102** [comment]
Ah ok i imaged pickup permission would be enough like if you cant pickup a slime then you cant detect a slime chunk that was the idea but oh well
Will add tweakin.slimebucket.detect in next one

**Comment by Brickwrath** [comment]
Coolio; thanks!
Yeah, the permission addition already solves the problem for sure, so that makes sense.
Greatly appreciated, especially since this feature is obviously for slime chunks.  Having this permission/option allows the tweak to then optionally be *just* a slime-bucket feature, which is honestly pretty cute/cool.

**Comment by sachingorkar102** [comment]
added in 1.8 update
