### ISSUE TITLE
Duplication glitch with shulkers

### ISSUE THREAD

**Issue by rockrevenchy** [sachingorkar102/tweakin#9]
I'm on tweakin 1.7 on a airplane-purpur server (fork of tuinity/paper/purpur) 1.17.1

If one would open a shulker box using the shift click method and then proceed to select a slot inside the shulker with their cursor and then press on a number from 1 to 9 that correspond to the now opened shulker's slot number, the shulker will seemingly vanish from the player's hands and go inside itself, on the selected slot, once you close the shulker, it will reappear in your inventory, however, since it was also moved inside itself before we closed the inventory, this results in a shulker box duplication in the end

you may reopen the shulker box to find a duplicate of itself inside.

**Comment by rockrevenchy** [comment]
(btw, nice plugin, waited a while to find a plugin exactly like what you did here, ill be looking forward to it)

**Comment by sachingorkar102** [comment]
fixed in 1.9 update
